// electron/services/printer.js
const { exec } = require("child_process");
const fs = require("fs");
const path = require("path");
const { app } = require("electron");

function setupPrinter() {
  console.log("Printer service ready");
}

async function printReceipt(receiptData) {
  const { businessName, items, subtotal, discount, vatRate, vatAmount, total, paymentMethod, amountPaid, changeAmount, footer } = receiptData;

  const receipt = `
    ${businessName || "SmartPOS"}
    ${new Date().toLocaleString()}
    
    ${items.map((item) => `${item.name} x${item.quantity}`.padEnd(20) + `${(item.price * item.quantity).toFixed(2)}`.padStart(10)).join("\n")}
    ----------------------------------------
    Subtotal:${String(subtotal?.toFixed(2) || "0.00").padStart(23)}
    ${discount > 0 ? `Discount:${String((-discount).toFixed(2)).padStart(24)}` : ""}
    ${vatAmount > 0 ? `VAT (${vatRate}%):${String(vatAmount.toFixed(2)).padStart(19)}` : ""}
    TOTAL:${String(total?.toFixed(2) || "0.00").padStart(27)}
    Payment: ${paymentMethod || "cash"}
    ${amountPaid ? `Paid: ${amountPaid.toFixed(2)}  Change: ${changeAmount?.toFixed(2) || "0.00"}` : ""}
    ----------------------------------------
    ${footer || "Thank you for shopping with us!"}
    
    Generated by SmartPOS Desktop
  `;

  try {
    const tempPath = path.join(app.getPath("temp"), `receipt-${Date.now()}.txt`);
    fs.writeFileSync(tempPath, receipt);

    if (process.platform === "win32") {
      exec(`notepad /p "${tempPath}"`);
    } else if (process.platform === "darwin") {
      exec(`lp "${tempPath}"`);
    } else {
      exec(`lp "${tempPath}"`);
    }

    return { success: true };
  } catch (err) {
    console.error("Print failed:", err.message);
    return { success: false, error: err.message };
  }
}

module.exports = { setupPrinter, printReceipt };